### ISSUE TITLE
Improve validation scripts

### ISSUE THREAD

**Issue by akorosov** [nansencenter/sentinel1denoised#55]
1. Split the script into two parts: 1: for processing individual files (like run_experiments_...), 2: for averaging, plotting, making tables (like analyze_experiment_...
2. Plot one extra bar with averaged difference [(q_esa[i] - q_nesrc[i]) for i in range(n)] / n
3. Plot individual regions and aggregate 15 bars on one chart: esa,ners,diff for 5 regions

**Comment by xdenisx** [comment]
1. Done in 'run_qam.py' and 'analyze_qam.py' in the 'validation' folder
2. Done
3. Partially prepared
